-- 092_seed_wccg_content — ports hardcoded shows/hosts/check-ins into the DB (station_wccg). Generated from apps/web/src/data/*.ts.

begin;

-- ── Additive columns (idempotent) ──────────────────────────────────────────
alter table public.shows add column if not exists host_names      text;
alter table public.shows add column if not exists tagline         text;
alter table public.shows add column if not exists show_image_url  text;
alter table public.shows add column if not exists host_image_url  text;
alter table public.shows add column if not exists category        text;

alter table public.hosts add column if not exists youtube_channel text;

alter table public.check_in_locations add column if not exists description text;

-- ── Stream for MixxSquadd Radio (so its show has a valid stream_id) ─────────
insert into public.streams (id, name, slug, category, status, station_id) values
  ('stream_mixsquad', 'MixxSquadd', 'mixsquad', 'HIP_HOP', 'ACTIVE', 'station_wccg')
on conflict (id) do nothing;

-- ── Shows ───────────────────────────────────────────────────────────────────
insert into public.shows
  (id, name, slug, host_names, time_slot, days, description, tagline, gradient,
   image_url, show_image_url, host_image_url, hero_image_class, youtube, podcast_rss,
   segments, is_syndicated, is_active, category, stream_id, station_id)
values
  ('show_streetz_morning', 'Yung Joc and The Streetz Morning Takeover', 'streetz-morning-takeover', 'Yung Joc, Mz Shyneka & Shawty Shawty', '6:00 AM - 10:00 AM', 'Monday - Friday', 'North Carolina''s #1 Hip-Hop morning show on WCCG 104.5 FM, hosted by Yung Joc, Mz Shyneka, and Shawty Shawty. It''s a high-energy mix of the hottest Hip-Hop & R&B, celebrity gossip, viral trending topics, relationship drama (Date Dilemma), wild news (Shawty''s Crazy Report), and non-stop laughs — the unfiltered soundtrack that wakes up the city and the culture every weekday.', 'North Carolina''s #1 Hip-Hop Morning Show', 'from-[#1a0a2e] via-[#16213e] to-[#0f3460]', '/images/hosts/yung-joc.png', 'https://wccg1045fm.com/wp-content/uploads/2025/09/streetz.png', 'https://wccg1045fm.com/wp-content/uploads/2025/11/attachment-thumbnail_new-streetz-pix.png', 'object-cover object-top', '{"channelName":"Streetz Morning Takeover","channelUrl":"https://youtube.com/@WCCG1045FM","searchQuery":"Streetz Morning Takeover WCCG"}'::jsonb, 'https://feeds.simplecast.com/c3z3h1Ug', '["Date Dilemma","Shawty''s Crazy Report","Celebrity Interviews","Trending Topics"]'::jsonb, true, true, 'weekday', 'stream_main', 'station_wccg'),
  ('show_way_up_angela_yee', 'Way Up with Angela Yee', 'way-up-angela-yee', 'Angela Yee', '10:00 AM - 2:00 PM', 'Monday - Friday', 'The syndicated midday Hip-Hop and R&B powerhouse featuring witty, empowering vibes with trending topics, relationship advice, anonymous secrets, and A-list interviews. Angela Yee is the ultimate midday motivator for urban listeners nationwide.', 'The ultimate midday motivator', 'from-[#1a0533] via-[#2d1b69] to-[#1a1a2e]', 'https://wccg1045fm.com/wp-content/uploads/2025/09/angela-yee-new-2.png', 'https://wccg1045fm.com/wp-content/uploads/2025/09/yee-01.png', 'https://wccg1045fm.com/wp-content/uploads/2025/11/angela-yee-tamara-beckwith-ny-post-01.webp', NULL, '{"channelName":"Way Up With Angela Yee","channelUrl":"https://www.youtube.com/@wayupwithyee","channelId":"UCJVR_M2dXZT6uXIapYGHtTA","extraChannelIds":["UCWS_UtIkoPGKODjeJEHMdEg"],"searchQuery":"Way Up With Angela Yee"}'::jsonb, NULL, '["Shine a Light on ''Em","Tell Us a Secret","Rumor Report","Ask Yee"]'::jsonb, true, true, 'weekday', 'stream_main', 'station_wccg'),
  ('show_general_programming_weekday', 'General Programming', 'general-programming-afternoon', 'WCCG', '2:00 PM - 7:00 PM', 'Monday - Friday', 'WCCG 104.5 FM brings you the best in hip hop and R&B during the afternoon drive. Featuring today''s daily mix show theme and the hottest tracks to power your commute home.', 'Afternoon drive with the best hip hop and R&B', 'from-[#0f0c29] via-[#302b63] to-[#24243e]', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, false, true, 'weekday', 'stream_main', 'station_wccg'),
  ('show_posted_corner', 'Posted on The Corner', 'posted-on-the-corner', 'Incognito & DJ Misses', '7:00 PM - Midnight', 'Monday - Friday', 'The syndicated weeknight Hip-Hop and R&B party show featuring high-energy vibes, exclusive celebrity interviews, fan-voted Top 7 Countdowns, wild Trending on the Timeline segments, and interactive trivia that turns listeners into the real stars of the show. Airing in over 20 markets including Atlanta, Houston, Dallas, Cleveland, Baltimore, Detroit, Indianapolis, and Raleigh.', 'The syndicated weeknight Hip-Hop party in 20+ markets', 'from-[#0a1628] via-[#1a0a2e] to-[#162447]', '/images/incognito-new.png', '/images/incognito-new.png', '/images/incognito-new.png', NULL, '{"channelName":"Posted On The Corner","channelUrl":"https://www.youtube.com/@PostedOnTheCorner","channelId":"UCB4JlD2jIkXanFehab9CbDw","searchQuery":"Posted on The Corner"}'::jsonb, NULL, '["Top 7 Countdown","Posted on The Corner Trivia","Trending on the Timeline","Celebrity Interviews"]'::jsonb, true, true, 'weekday', 'stream_main', 'station_wccg'),
  ('show_bootleg_kev', 'The Bootleg Kev Show', 'bootleg-kev-show', 'Bootleg Kev, James Andre Jefferson Jr. & DJ Sam I Am', 'Midnight - 6:00 AM', 'Monday - Friday', 'A nationally syndicated hip-hop overnight program featuring exclusive artist interviews, viral freestyles, No Cap News, wild caller roasts, and non-stop bangers. Bootleg Kev, James Andre Jefferson Jr., and DJ Sam I Am target night-shift workers, insomniacs, and late-night culture enthusiasts across 80+ stations with raw, unfiltered hip-hop culture and celebrity access.', 'Overnight hip-hop across 80+ stations', 'from-[#1a0533] via-[#0d1b2a] to-[#1b2838]', 'https://wccg1045fm.com/wp-content/uploads/2025/09/bootleg-kev-new1.png', 'https://wccg1045fm.com/wp-content/uploads/2025/09/bootleg-kev-new1.png', 'https://wccg1045fm.com/wp-content/uploads/2025/11/GAxhqlAXcAAPZOQ.jpg', NULL, '{"channelName":"Bootleg Kev","channelUrl":"https://www.youtube.com/@BootlegKev","channelId":"UCBgOGeH-NL4o2WGutwverqQ","searchQuery":"Bootleg Kev"}'::jsonb, NULL, '["No Cap News","Artist Freestyles","Pop Culture Debates","Listener Call-ins"]'::jsonb, true, true, 'weekday', 'stream_main', 'station_wccg'),
  ('show_abc_news', 'ABC News Updates', 'abc-news', 'ABC News', 'Hourly', 'Monday - Friday', 'Stay informed with ABC News updates airing throughout the day on WCCG 104.5 FM. National and world news coverage keeping you connected to breaking stories and trending topics.', 'National news updates throughout the day', 'from-[#0a0a1a] via-[#1a1a2e] to-[#16213e]', NULL, NULL, NULL, NULL, '{"channelName":"ABC News","channelUrl":"https://www.youtube.com/@ABCNews","channelId":"UCBi2mrWuNuyYy4gbM6fU18Q","searchQuery":"ABC News"}'::jsonb, NULL, '[]'::jsonb, true, true, 'weekday', 'stream_main', 'station_wccg'),
  ('show_streetz_weekend_countdown', 'Yung Joc and the Streetz Weekend Countdown', 'streetz-weekend-countdown', 'Yung Joc, Mz Shyneka & Shawty Shawty', '6:00 AM - 9:00 AM', 'Saturday', 'The Streetz Morning Takeover crew brings the same high energy to Saturday mornings with the Streetz Weekend Countdown. Top tracks, celebrity moments, and the best recaps of the week.', 'Saturday morning countdown of the week''s hottest tracks', 'from-[#1a0a2e] via-[#16213e] to-[#0f3460]', '/images/hosts/yung-joc.png', '/images/shows/streetz-morning-takeover.png', NULL, NULL, NULL, NULL, '[]'::jsonb, true, true, 'saturday', 'stream_main', 'station_wccg'),
  ('show_deja_vu', 'The Deja Vu Show', 'deja-vu-show', 'WCCG', '10:00 AM - 3:00 PM', 'Saturday', 'Take a trip down memory lane with The Deja Vu Show. Featuring classic hip hop, R&B throwbacks, and nostalgic hits that bring the good vibes every Saturday.', 'Classic throwbacks and nostalgic vibes every Saturday', 'from-[#1a1a2e] via-[#2d1b69] to-[#1a0533]', NULL, NULL, NULL, NULL, '{"channelName":"The Deja Vu Show","channelUrl":"https://www.youtube.com/@TheDejaVuShow","channelId":"UCO_M1X6yEa-T1UH_XhWA8Yw","searchQuery":"The Deja Vu Show WCCG"}'::jsonb, NULL, '[]'::jsonb, false, true, 'saturday', 'stream_main', 'station_wccg'),
  ('show_day_party', 'Day Party Radio: The Weekend Top 50', 'day-party-radio', 'WCCG', '3:00 PM - 7:00 PM', 'Saturday', 'Get the party started early with Day Party Radio featuring The Weekend Top 50 countdown. High-energy mixes and the hottest tracks of the week to kick off your Saturday night.', 'The Weekend Top 50 — get the party started before the sun goes down', 'from-[#0f3460] via-[#16213e] to-[#162447]', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, false, true, 'saturday', 'stream_main', 'station_wccg'),
  ('show_riich_villianz', 'Riich Villianz Radio', 'riich-villianz-radio', 'DJ Ricovelli, Slim & DJ Tony Neal', '7:00 PM - Midnight', 'Saturday', 'DJ Ricovelli, Slim, and the legendary DJ Tony Neal (founder of Core DJs) take over Saturday nights with Riich Villianz Radio. The hottest mixes, exclusive drops, and non-stop party energy.', 'Saturday night takeover with the hottest DJ mixes', 'from-[#1a0533] via-[#0f0c29] to-[#302b63]', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, false, true, 'saturday', 'stream_main', 'station_wccg'),
  ('show_general_programming_sat_overnight', 'Overnights', 'saturday-overnights', 'WCCG', 'Midnight - 6:00 AM', 'Saturday', 'General programming through the early Saturday morning hours featuring the best in hip hop and R&B.', 'Late night general programming', 'from-[#0f0c29] via-[#1a0533] to-[#24243e]', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, false, true, 'saturday', 'stream_main', 'station_wccg'),
  ('show_praise_mix', 'Praise Mix at 6am', 'praise-mix', 'WCCG', '6:00 AM - 8:00 AM', 'Sunday', 'Start your Sunday morning with an uplifting mix of gospel music, praise and worship, and inspirational tracks. Part of The Sunday Gospel Caravan on WCCG 104.5 FM.', 'Start your Sunday with praise and worship', 'from-[#1a1a2e] via-[#16213e] to-[#0d1b2a]', NULL, 'https://wccg1045fm.com/wp-content/uploads/2025/12/praisemix-6.png', NULL, NULL, NULL, NULL, '[]'::jsonb, false, true, 'gospel', 'stream_main', 'station_wccg'),
  ('show_grace_plus_nothing', 'Grace Plus Nothing Ministries', 'grace-plus-nothing', 'Apostle Anthony Monds', '8:00 AM - 9:00 AM', 'Sunday', 'Apostle Anthony Monds brings messages of faith, grace, and community as part of the Sunday Gospel Caravan on WCCG 104.5 FM.', 'Messages of faith, grace, and community', 'from-[#1a1a2e] via-[#0d1b2a] to-[#16213e]', NULL, 'https://wccg1045fm.com/wp-content/uploads/2025/10/gpn-1-1024x743-1.png', NULL, NULL, '{"channelName":"Grace Plus Nothing","channelUrl":"https://www.youtube.com/@anthonymonds3736","channelId":"UCRqRVNSRMdIQqZw60bAgN1w","searchQuery":"Grace Plus Nothing Ministries"}'::jsonb, NULL, '[]'::jsonb, false, true, 'gospel', 'stream_main', 'station_wccg'),
  ('show_encouraging_moment', 'The Encouraging Moment', 'encouraging-moment', 'Dr. Tony Haire', '9:00 AM - 10:00 AM', 'Sunday', 'Dr. Tony Haire provides spiritual encouragement, biblical teaching, and hope to the Fayetteville community and beyond every Sunday morning as part of The Sunday Gospel Caravan.', 'Spiritual encouragement and biblical teaching', 'from-[#16213e] via-[#1a1a2e] to-[#0d1b2a]', NULL, 'https://wccg1045fm.com/wp-content/uploads/2025/10/thm-main-1024x743-1.png', NULL, NULL, '{"channelName":"Encouraging Moments","channelUrl":"https://www.youtube.com/@encouraging1moment","channelId":"UCvxWyn4rfcI2H9APhfUIB1Q","searchQuery":"Encouraging Moments Dr Anthony Haire"}'::jsonb, NULL, '[]'::jsonb, false, true, 'gospel', 'stream_main', 'station_wccg'),
  ('show_marvin_sapp', 'The Marvin Sapp Radio Show', 'marvin-sapp-radio-show', 'Bishop Marvin Sapp', '10:00 AM - 12:00 PM', 'Sunday', 'Multi-Grammy nominated gospel artist and pastor Bishop Marvin Sapp brings inspirational conversation, the best in gospel music, and uplifting messages every Sunday morning.', 'Inspirational gospel from a Grammy-nominated artist', 'from-[#1a0533] via-[#2d1b69] to-[#1a1a2e]', NULL, 'https://wccg1045fm.com/wp-content/uploads/2025/10/marvin-sapp12.jpg', NULL, NULL, NULL, NULL, '[]'::jsonb, true, true, 'gospel', 'stream_main', 'station_wccg'),
  ('show_family_fellowship', 'Family Fellowship Worship Center', 'family-fellowship', 'FFWC', '12:00 PM - 1:00 PM', 'Sunday', 'Family Fellowship Worship Center brings their Sunday service to the airwaves with powerful sermons and spiritual guidance.', 'Powerful sermons and spiritual guidance', 'from-[#0d1b2a] via-[#1a1a2e] to-[#16213e]', NULL, 'https://wccg1045fm.com/wp-content/uploads/2025/10/ffwc-1024x743-1.png', NULL, NULL, '{"channelName":"Family Fellowship Worship Center","channelUrl":"https://www.youtube.com/@weareffwc","channelId":"UCxTzK_2da5bZag5WTAbiVzQ","searchQuery":"Family Fellowship Worship Center"}'::jsonb, NULL, '[]'::jsonb, false, true, 'gospel', 'stream_main', 'station_wccg'),
  ('show_progressive_mbc', 'Progressive Missionary Baptist Church', 'progressive-mbc', 'Rev. F. Bernard Fuller', '1:00 PM - 2:00 PM', 'Sunday', 'Reverend F. Bernard Fuller leads Progressive Missionary Baptist Church — relevant, radical, and real faith through strong biblical teaching — broadcast as part of The Sunday Gospel Caravan.', 'Relevant, radical, and real faith', 'from-[#0d1b2a] via-[#16213e] to-[#1a1a2e]', NULL, 'https://wccg1045fm.com/wp-content/uploads/2025/10/progressive-1024x743-1.png', NULL, NULL, '{"channelName":"Progressive Missionary Baptist Church","channelUrl":"https://www.youtube.com/@progressivemissionarybapti7744","channelId":"UCavo4QHyzuMM2FED2W6PwEg","searchQuery":"Progressive Missionary Baptist Church Fayetteville"}'::jsonb, NULL, '[]'::jsonb, false, true, 'gospel', 'stream_main', 'station_wccg'),
  ('show_lewis_chapel', 'Lewis Chapel Baptist Church', 'lewis-chapel', 'Pastor Christopher Stackhouse', '2:00 PM - 3:00 PM', 'Sunday', 'Pastor Christopher Stackhouse leads the Lewis Chapel Baptist Church broadcast every Sunday afternoon as part of The Sunday Gospel Caravan.', 'Inspirational Sunday afternoon messages', 'from-[#1a1a2e] via-[#16213e] to-[#0d1b2a]', NULL, 'https://wccg1045fm.com/wp-content/uploads/2025/10/lewis-chapel-1024x743-1.png', NULL, NULL, '{"channelName":"Lewis Chapel Missionary Baptist Church","channelUrl":"https://www.youtube.com/@lewischapelmissionarybapti4024","channelId":"UCOe1fQxFPHNf3N7Rb55ySTA","searchQuery":"Lewis Chapel Missionary Baptist Church"}'::jsonb, NULL, '[]'::jsonb, false, true, 'gospel', 'stream_main', 'station_wccg'),
  ('show_general_programming_sunday', 'General Programming', 'general-programming-sunday', 'WCCG', '3:00 PM - 7:00 PM', 'Sunday', 'Wind down the weekend with the best in R&B and hip hop as we wrap up Sunday and get you ready for the week ahead. Featuring the Shorty Corleone Gogo Mix Show at 5pm.', 'Wrapping up the weekend with the best music', 'from-[#0f3460] via-[#16213e] to-[#1a1a2e]', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, false, true, 'sunday', 'stream_main', 'station_wccg'),
  ('show_gogo_mix', 'Crank with Shorty Corleone', 'crank-shorty-corleone', 'Shorty Corleone', '5:00 PM - 6:00 PM', 'Sunday', 'Go-Go legend Shorty Corleone cranks up Fayetteville with one hour of pure DMV fire — blending D.C.''s pocket-heavy classics from Rare Essence and Chuck Brown with fresh Hip-Hop remixes, live scratches, and call-in shoutouts. A Rare Essence alumnus with a Warner Bros. publishing deal at age 14, Corleone also co-hosts Sirius XM''s syndicated Crank Radio on H.U.R. Voices.', 'One hour of pure DMV fire every Sunday', 'from-[#302b63] via-[#0f0c29] to-[#1a0533]', 'https://wccg1045fm.com/wp-content/uploads/2025/11/shorty-corleone-new.png', 'https://wccg1045fm.com/wp-content/uploads/2025/11/shorty-corleone-new.png', 'https://wccg1045fm.com/wp-content/uploads/2025/11/shorty-corleone.png', NULL, NULL, NULL, '[]'::jsonb, false, true, 'sunday', 'stream_main', 'station_wccg'),
  ('show_sunday_snacks', 'Sunday Snacks', 'sunday-snacks', 'DJ Ike GDA & DJ IzzyNice', '7:00 PM - Midnight', 'Sunday', 'The Wright Brothers of the turntables deliver five straight hours of soul food for your speakers: classic throwbacks, brand-new heat, exclusive remixes, and live scratches that make the subs knock. DJ Ike GDA, a veteran turntablist and Carolina Trendsetter with three decades in Southern hip-hop, teams with DJ IzzyNice, a high-octane mixer with 20+ years in Carolina nightlife.', 'Five hours of soul food for your speakers', 'from-[#302b63] via-[#0f0c29] to-[#24243e]', '/images/WRIGHT-BROS.png', '/images/WRIGHT-BROS.png', '/images/WRIGHT-BROS.png', 'object-cover object-center', NULL, NULL, '[]'::jsonb, false, true, 'sunday', 'stream_main', 'station_wccg'),
  ('show_island_frequency', 'The Island Frequency Podcast', 'island-frequency-podcast', 'DJ Daffie', 'Sunday Evenings', 'Sunday', 'DJ Daffie brings Caribbean and island vibes to the airwaves with The Island Frequency Podcast. A DJ and performer from Queens/Long Island, New York, Daffie blends dancehall, soca, reggae, and Afrobeats with hip-hop for a unique island-urban fusion.', 'Caribbean vibes and island-urban fusion', 'from-[#0f3460] via-[#16213e] to-[#1a0533]', 'https://wccg1045fm.com/wp-content/uploads/2026/02/island-freq.png', 'https://wccg1045fm.com/wp-content/uploads/2026/02/island-freq.png', 'https://wccg1045fm.com/wp-content/uploads/2026/02/IMG_5248-5-scaled.jpg', NULL, NULL, NULL, '[]'::jsonb, false, true, 'sunday', 'stream_main', 'station_wccg'),
  ('show_mixsquad_radio', 'MixxSquadd Radio', 'mixsquad-radio', 'DJ Ricovelli, DJ SpinWiz, DJ Rayn, DJ TommyGee Mixx & DJ Yodo', '24/7', 'Every Day', 'MixxSquadd Radio delivers non-stop DJ mixes 24/7 on its own dedicated stream. Featuring DJ Ricovelli, DJ SpinWiz, DJ Rayn, DJ TommyGee Mixx, and DJ Yodo with the best in hip hop, R&B, dancehall, and club mixes.', '24/7 non-stop DJ mixes on a dedicated stream', 'from-[#ec4899] via-[#be185d] to-[#831843]', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, false, true, 'mixsquad', 'stream_mixsquad', 'station_wccg'),
  ('show_big_cas', 'Big Cas', 'big-cas', 'Big Cas', 'On Demand', 'New episodes weekly', 'Big Cas brings Fayetteville the culture unfiltered — hip-hop news, reactions, interviews, and the stories moving the 910. Straight talk from Fayettenam''s own. Contains explicit language.', 'Fayettenam culture, unfiltered', 'from-[#1a0533] via-[#2d0a4e] to-[#0a0a1a]', NULL, NULL, NULL, NULL, '{"channelName":"BigCas910 TV","channelUrl":"https://www.youtube.com/@bigcas910","channelId":"UCQmsI0AAbXvTevWkqMIBU-Q","searchQuery":"BigCas910 TV"}'::jsonb, NULL, '[]'::jsonb, false, true, 'mixsquad', 'stream_main', 'station_wccg'),
  ('show_carolina_effect', 'The Carolina Effect', 'carolina-effect', 'WCCG', 'On Demand', 'Weekly', 'A deep dive into Carolina culture — music, sports, lifestyle, and the people shaping the Carolinas. Real conversations with local influencers, artists, and community leaders.', 'The pulse of Carolina culture', 'from-[#1e3a5f] via-[#0d2137] to-[#0a0a0f]', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, false, true, 'weekday', 'stream_main', 'station_wccg'),
  ('show_inside_the_lines', 'Inside The Lines with James Sanders III', 'inside-the-lines', 'James Sanders III', 'On Demand', 'Weekly', 'Sports analyst James Sanders III goes beyond the box scores to bring listeners the stories, strategy, and culture behind the games. From college hoops to the NFL, Inside The Lines delivers expert analysis with a Carolina perspective.', 'Beyond the box scores', 'from-[#003087] via-[#001f5c] to-[#0a0a0f]', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, false, true, 'weekday', 'stream_main', 'station_wccg'),
  ('show_friday_night_shockwave', 'Friday Night Shockwave', 'friday-night-shockwave', 'WCCG', 'Friday Nights', 'Friday', 'The ultimate Friday night experience — non-stop bangers, exclusive mixes, and high-voltage energy to kick off your weekend. Friday Night Shockwave delivers the hardest-hitting playlist on Carolina radio.', 'High-voltage Friday nights', 'from-[#dc2626] via-[#7401df] to-[#0a0a0f]', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb, false, true, 'weekday', 'stream_main', 'station_wccg')
on conflict (id) do update set
  name           = excluded.name,
  slug           = excluded.slug,
  host_names     = excluded.host_names,
  time_slot      = excluded.time_slot,
  days           = excluded.days,
  description    = excluded.description,
  tagline        = excluded.tagline,
  gradient       = excluded.gradient,
  image_url      = excluded.image_url,
  show_image_url = excluded.show_image_url,
  host_image_url = excluded.host_image_url,
  hero_image_class = excluded.hero_image_class,
  youtube        = excluded.youtube,
  podcast_rss    = excluded.podcast_rss,
  segments       = excluded.segments,
  is_syndicated  = excluded.is_syndicated,
  is_active      = excluded.is_active,
  category       = excluded.category,
  stream_id      = excluded.stream_id,
  station_id     = excluded.station_id;

-- ── Hosts ───────────────────────────────────────────────────────────────────
insert into public.hosts
  (id, name, slug, role, bio, avatar_url, social_links, youtube_channel,
   youtube_channel_id, is_syndicated, is_active, category, station_id)
values
  ('host_yung_joc', 'Yung Joc', 'yung-joc', 'Host', 'Rapper, DJ, and radio personality Yung Joc brings high energy and unfiltered takes to the Streetz Morning Takeover. Known for his hit ''It''s Goin'' Down'' and his dynamic presence on Love & Hip Hop Atlanta, Joc delivers the hottest conversations, celebrity interviews, and the best morning mix of hip hop and R&B every weekday.', '/images/hosts/yung-joc.png', '[{"platform":"instagram","url":"https://instagram.com/jaborafaeldavismcintyre","label":"@jaborafaeldavismcintyre"},{"platform":"twitter","url":"https://x.com/IBLOCKYOU","label":"@IBLOCKYOU"}]'::jsonb, NULL, NULL, true, true, 'main', 'station_wccg'),
  ('host_mz_shyneka', 'Mz. Shyneka', 'mz-shyneka', 'Co-Host', 'Mz. Shyneka is the co-host of the Streetz Morning Takeover, bringing her witty personality, sharp commentary, and undeniable chemistry with the crew. She keeps the conversation real and the energy high every morning.', NULL, '[{"platform":"instagram","url":"https://instagram.com/mikiamz.shyneka","label":"@mikiamz.shyneka"}]'::jsonb, NULL, NULL, true, true, 'main', 'station_wccg'),
  ('host_shawty_shawty', 'Shawty Shawty', 'shawty-shawty', 'Co-Host', 'Shawty Shawty rounds out the Streetz Morning Takeover crew with his unique perspective and humor. Together with Yung Joc and Mz. Shyneka, he helps deliver the morning show that wakes up the streets.', NULL, '[]'::jsonb, NULL, NULL, true, true, 'main', 'station_wccg'),
  ('host_dj_swin', 'DJ Swin', 'dj-swin', 'DJ', 'DJ Swin keeps the music flowing as the official DJ of the Streetz Morning Takeover. His mixes set the tone every morning with the perfect blend of hip hop, R&B, and trending tracks.', NULL, '[]'::jsonb, NULL, NULL, true, true, 'main', 'station_wccg'),
  ('host_et_cali', 'ET Cali', 'et-cali', 'Fill-In', 'ET Cali serves as a fill-in host for the Streetz Morning Takeover, stepping in with his own brand of energy and entertainment when the crew needs backup.', NULL, '[]'::jsonb, NULL, NULL, true, true, 'main', 'station_wccg'),
  ('host_angela_yee', 'Angela Yee', 'angela-yee', 'Host', 'Angela Yee is a media mogul, entrepreneur, and the host of Way Up with Angela Yee, syndicated nationally through Premiere Networks/iHeartRadio. Previously co-hosting the legendary Breakfast Club for over a decade, Angela brings celebrity interviews, relationship advice, trending topics, and cultural commentary to midday radio.', '/images/hosts/angela-yee.png', '[{"platform":"instagram","url":"https://instagram.com/angelayee","label":"@angelayee"},{"platform":"twitter","url":"https://x.com/angelayee","label":"@angelayee"},{"platform":"youtube","url":"https://youtube.com/@wayupwithyee","label":"@wayupwithyee"}]'::jsonb, '@wayupwithyee', 'UCJVR_M2dXZT6uXIapYGHtTA', true, true, 'main', 'station_wccg'),
  ('host_incognito', 'Incognito', 'incognito', 'Host', 'Incognito is the voice of Posted on the Corner, syndicated in 20+ markets nationwide. Known as Ncognito on some platforms, he delivers the hardest hip hop, exclusive freestyles, and unfiltered commentary every evening. From new music drops to street culture, The Corner is where the streets meet the airwaves.', '/images/hosts/incognito.png', '[{"platform":"instagram","url":"https://instagram.com/ncognito","label":"@ncognito"},{"platform":"twitter","url":"https://x.com/ncognito","label":"@ncognito"}]'::jsonb, NULL, NULL, true, true, 'main', 'station_wccg'),
  ('host_dj_misses', 'DJ Misses', 'dj-misses', 'Co-Host', 'DJ Misses co-hosts Posted on the Corner alongside Incognito, keeping the mixes fresh and the energy up every evening. Her skills behind the decks complement the raw takes and conversation.', NULL, '[]'::jsonb, NULL, NULL, true, true, 'main', 'station_wccg'),
  ('host_bootleg_kev', 'Bootleg Kev', 'bootleg-kev', 'Host', 'Bootleg Kev is a nationally syndicated radio host through Premiere Networks, known for his exclusive interviews with the biggest names in hip hop. With 468K+ YouTube subscribers, Kev connects listeners with first-listen sessions, behind-the-scenes industry stories, and breaking music from coast to coast.', NULL, '[{"platform":"youtube","url":"https://youtube.com/@bootlegkev","label":"@bootlegkev"},{"platform":"instagram","url":"https://instagram.com/bootlegkev","label":"@bootlegkev"},{"platform":"twitter","url":"https://x.com/bootlegkev","label":"@bootlegkev"}]'::jsonb, '@bootlegkev', 'UCBgOGeH-NL4o2WGutwverqQ', true, true, 'main', 'station_wccg'),
  ('host_shorty_corleone', 'Shorty Corleone', 'shorty-corleone', 'Host', 'Shorty Corleone brings certified bangers, underground hip hop, and the best in Southern rap every weeknight on Crank. From trap classics to new fire, Crank is the soundtrack for the late night.', '/images/hosts/shorty-corleone.png', '[]'::jsonb, NULL, NULL, false, true, 'main', 'station_wccg'),
  ('host_dj_ricovelli', 'DJ Ricovelli', 'dj-ricovelli', 'DJ', 'DJ Ricovelli is a core member of both Rich Villianz Radio and MixxSquadd Radio. As one of the featured Saturday night DJs, he brings high-energy sets blending hip hop, trap, and club tracks to keep the party going all night.', '/images/hosts/dj-ricoveli.png', '[]'::jsonb, NULL, NULL, false, true, 'weekend', 'station_wccg'),
  ('host_dj_tony_neal', 'DJ Tony Neal', 'dj-tony-neal', 'DJ', 'DJ Tony Neal is the founder of Core DJs, one of the most influential DJ coalitions in the industry. He brings his legendary mixing skills and deep industry connections to Rich Villianz Radio every Saturday night.', '/images/hosts/dj-tony-neal.png', '[{"platform":"website","url":"https://djtonyneal.com","label":"djtonyneal.com"},{"platform":"instagram","url":"https://instagram.com/djtonyneal","label":"@djtonyneal"}]'::jsonb, NULL, NULL, false, true, 'weekend', 'station_wccg'),
  ('host_carolina_trendsetter', 'Carolina Trendsetter', 'carolina-trendsetter', 'DJ', 'Carolina Trendsetter anchors Sunday Snacks alongside DJ Ike GDA and DJ Izzynice, bringing the best in regional hip hop and DJ mixes every Sunday night to close out the weekend.', NULL, '[]'::jsonb, NULL, NULL, false, true, 'sunday', 'station_wccg'),
  ('host_dj_ike_gda', 'DJ Ike GDA', 'dj-ike-gda', 'DJ', 'DJ Ike GDA is part of the Sunday Snacks crew, delivering club-ready mixes and the hottest tracks to wrap up the weekend right.', '/images/hosts/dj-ike-gda.png', '[]'::jsonb, NULL, NULL, false, true, 'sunday', 'station_wccg'),
  ('host_dj_izzynice', 'DJ Izzynice', 'dj-izzynice', 'DJ', 'DJ Izzynice rounds out the Sunday Snacks team, bringing smooth transitions and eclectic selections to the Sunday night mix.', '/images/hosts/dj-izzynice.png', '[]'::jsonb, NULL, NULL, false, true, 'sunday', 'station_wccg'),
  ('host_marvin_sapp', 'Bishop Marvin Sapp', 'marvin-sapp', 'Bishop', 'Bishop Marvin Sapp is a multi-Grammy nominated gospel artist and pastor. The Marvin Sapp Radio Show blends inspirational conversation, gospel music, and uplifting messages every Sunday morning. Known worldwide for his timeless hit ''Never Would Have Made It.''', NULL, '[{"platform":"instagram","url":"https://instagram.com/bishopmarvinlsapp","label":"@bishopmarvinlsapp"}]'::jsonb, NULL, NULL, true, true, 'gospel', 'station_wccg'),
  ('host_apostle_monds', 'Apostle Anthony Monds', 'apostle-monds', 'Pastor', 'Apostle Anthony Monds leads the Grace Plus Nothing Ministries broadcast every Sunday morning, sharing messages of faith, grace, and community as part of the Sunday Gospel Caravan on WCCG.', NULL, '[]'::jsonb, NULL, NULL, false, true, 'gospel', 'station_wccg'),
  ('host_dr_haire', 'Dr. Anthony Haire', 'dr-haire', 'Pastor', 'Dr. Anthony Haire hosts Encouraging Moments, a Sunday morning broadcast that provides spiritual encouragement, biblical teaching, and hope to the Fayetteville community and beyond.', NULL, '[]'::jsonb, NULL, NULL, false, true, 'gospel', 'station_wccg'),
  ('host_pastor_davenport', 'Pastor Dr. T.L. Davenport', 'pastor-davenport', 'Pastor', 'Pastor Dr. T.L. Davenport leads the Family Fellowship Worship Center broadcast, bringing powerful Sunday sermons and spiritual guidance to the WCCG 104.5 FM audience.', NULL, '[]'::jsonb, NULL, NULL, false, true, 'gospel', 'station_wccg'),
  ('host_rev_fuller', 'Rev. F. Bernard Fuller', 'rev-fuller', 'Pastor', 'Rev. F. Bernard Fuller brings the Sunday service from Progressive Missionary Baptist Church to the airwaves, reaching the community with faith-based programming each week.', NULL, '[]'::jsonb, NULL, NULL, false, true, 'gospel', 'station_wccg'),
  ('host_dr_stackhouse', 'Dr. Christopher Stackhouse, Sr.', 'dr-stackhouse', 'Pastor', 'Dr. Christopher Stackhouse, Sr. leads the Lewis Chapel Missionary Baptist Church broadcast every Sunday afternoon, providing inspirational messages and worship to the Fayetteville area.', NULL, '[]'::jsonb, NULL, NULL, false, true, 'gospel', 'station_wccg'),
  ('host_dj_spinwiz', 'DJ SpinWiz', 'dj-spinwiz', 'DJ', 'DJ SpinWiz is part of the MixxSquadd Radio roster, contributing to the 24/7 DJ mix stream with high-energy sets and creative blends.', '/images/hosts/dj-spinwiz.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_rayn', 'DJ Rayn', 'dj-rayn', 'DJ', 'DJ Rayn brings smooth transitions and diverse track selections to the MixxSquadd Radio 24/7 stream.', '/images/hosts/dj-rayn.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_tommygee', 'DJ TommyGee Mixx', 'dj-tommygee', 'DJ', 'DJ TommyGee Mixx is a featured DJ on MixxSquadd Radio, known for his party-rocking mixes that keep the energy going around the clock.', '/images/hosts/dj-tommygeemixx.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_yodo', 'DJ Yodo', 'dj-yodo', 'DJ', 'DJ Yodo rounds out the MixxSquadd Radio lineup, delivering non-stop mixes that span hip hop, R&B, dancehall, and more.', '/images/hosts/dj-yodo.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_chuck_t', 'DJ Chuck T', 'dj-chuck-t', 'DJ', 'DJ Chuck T is a legendary mixtape king and one of the most respected DJs in the Carolinas. Known for breaking records and rocking crowds, he brings certified street heat to the MixxSquadd.', '/images/hosts/dj-chuck-t.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_daddyblack', 'DJ DaddyBlack', 'dj-daddyblack', 'DJ', 'DJ DaddyBlack delivers raw energy and seamless transitions on MixxSquadd Radio, keeping the vibes right with his signature blends.', '/images/hosts/dj-daddyblack.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_daffie', 'DJ Daffie', 'dj-daffie', 'DJ', 'DJ Daffie keeps the party moving with infectious energy and creative mixes spanning hip hop, R&B, and Afrobeats on MixxSquadd Radio.', '/images/hosts/dj-daffie.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_dane_dinero', 'DJ Dane Dinero', 'dj-dane-dinero', 'DJ', 'DJ Dane Dinero brings a versatile style to MixxSquadd Radio, moving effortlessly between genres and keeping every set fresh.', '/images/hosts/dj-dane-dinero.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_itanist', 'DJ Itanist', 'dj-itanist', 'DJ', 'DJ Itanist is a creative force on MixxSquadd Radio, known for his innovative blends and electrifying live sets.', '/images/hosts/dj-itanist.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_jay_b', 'DJ Jay B', 'dj-jay-b', 'DJ', 'DJ Jay B brings smooth vibes and hard-hitting drops to MixxSquadd Radio, curating the perfect blend of hip hop and R&B.', '/images/hosts/dj-jay-b.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_juice', 'DJ Juice', 'dj-juice', 'DJ', 'DJ Juice serves up premium mixes on MixxSquadd Radio, blending old school classics with new school heat.', '/images/hosts/dj-juice.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_killako', 'DJ Killako', 'dj-killako', 'DJ', 'DJ Killako brings the energy with hard-hitting trap and hip hop mixes that keep the MixxSquadd Radio listeners locked in.', '/images/hosts/dj-killako.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_kingviv', 'DJ KingViv', 'dj-kingviv', 'DJ', 'DJ KingViv reigns over the turntables with regal precision, delivering sets that span hip hop, dancehall, and Afrobeats on MixxSquadd Radio.', '/images/hosts/dj-kingviv.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_lj', 'DJ LJ', 'dj-lj', 'DJ', 'DJ LJ keeps the crowd moving with seamless transitions and genre-bending mixes on MixxSquadd Radio.', '/images/hosts/dj-lj.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_loudiamonds', 'DJ Lou Diamonds', 'dj-loudiamonds', 'DJ', 'DJ Lou Diamonds shines bright on MixxSquadd Radio, delivering polished mixes with a signature style that keeps listeners coming back.', '/images/hosts/dj-loudiamonds.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_official', 'DJ Official', 'dj-official', 'DJ', 'DJ Official lives up to the name with certified club-ready mixes and high-energy sets on MixxSquadd Radio.', '/images/hosts/dj-official.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_swazzey', 'DJ Swazzey', 'dj-swazzey', 'DJ', 'DJ Swazzey brings the sauce with creative blends and innovative mixes that push boundaries on MixxSquadd Radio.', '/images/hosts/dj-swazzey.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_t_money', 'DJ T-Money', 'dj-t-money', 'DJ', 'DJ T-Money delivers premium mixes with a focus on Southern hip hop and club bangers on MixxSquadd Radio.', '/images/hosts/dj-t-money.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_tonelo', 'DJ Tonelo', 'dj-tonelo', 'DJ', 'DJ Tonelo sets the tone with smooth R&B blends and hard-hitting hip hop on MixxSquadd Radio.', '/images/hosts/dj-tonelo.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_weezy', 'DJ Weezy', 'dj-weezy', 'DJ', 'DJ Weezy brings non-stop energy with bass-heavy mixes and creative drops on MixxSquadd Radio.', '/images/hosts/dj-weezy.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_whosane', 'DJ Whosane', 'dj-whosane', 'DJ', 'DJ Whosane keeps the streets talking with certified mixes that blend trap, hip hop, and club music on MixxSquadd Radio.', '/images/hosts/dj-whosane.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_wolf', 'DJ Wolf', 'dj-wolf', 'DJ', 'DJ Wolf prowls the MixxSquadd Radio airwaves with aggressive mixes and high-octane energy that keeps the party alive.', '/images/hosts/dj-wolf.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg'),
  ('host_dj_yafeelme', 'DJ YaFeelMe', 'dj-yafeelme', 'DJ', 'DJ YaFeelMe connects with the listeners through feel-good mixes and undeniable vibes on MixxSquadd Radio.', '/images/hosts/dj-yafeelme.png', '[]'::jsonb, NULL, NULL, false, true, 'mixsquad', 'station_wccg')
on conflict (id) do update set
  name               = excluded.name,
  slug               = excluded.slug,
  role               = excluded.role,
  bio                = excluded.bio,
  avatar_url         = excluded.avatar_url,
  social_links       = excluded.social_links,
  youtube_channel    = excluded.youtube_channel,
  youtube_channel_id = excluded.youtube_channel_id,
  is_syndicated      = excluded.is_syndicated,
  is_active          = excluded.is_active,
  category           = excluded.category,
  station_id         = excluded.station_id;

-- ── Show ↔ Host links ───────────────────────────────────────────────────────
insert into public.show_hosts (show_id, host_id, is_primary, station_id) values
  ('show_streetz_morning', 'host_yung_joc', true, 'station_wccg'),
  ('show_streetz_morning', 'host_mz_shyneka', false, 'station_wccg'),
  ('show_streetz_morning', 'host_shawty_shawty', false, 'station_wccg'),
  ('show_streetz_morning', 'host_dj_swin', false, 'station_wccg'),
  ('show_streetz_morning', 'host_et_cali', false, 'station_wccg'),
  ('show_way_up_angela_yee', 'host_angela_yee', true, 'station_wccg'),
  ('show_posted_corner', 'host_incognito', true, 'station_wccg'),
  ('show_posted_corner', 'host_dj_misses', false, 'station_wccg'),
  ('show_bootleg_kev', 'host_bootleg_kev', true, 'station_wccg'),
  ('show_streetz_weekend_countdown', 'host_yung_joc', true, 'station_wccg'),
  ('show_streetz_weekend_countdown', 'host_mz_shyneka', false, 'station_wccg'),
  ('show_streetz_weekend_countdown', 'host_shawty_shawty', false, 'station_wccg'),
  ('show_riich_villianz', 'host_dj_ricovelli', true, 'station_wccg'),
  ('show_riich_villianz', 'host_dj_tony_neal', false, 'station_wccg'),
  ('show_grace_plus_nothing', 'host_apostle_monds', true, 'station_wccg'),
  ('show_encouraging_moment', 'host_dr_haire', true, 'station_wccg'),
  ('show_marvin_sapp', 'host_marvin_sapp', true, 'station_wccg'),
  ('show_progressive_mbc', 'host_rev_fuller', true, 'station_wccg'),
  ('show_gogo_mix', 'host_shorty_corleone', true, 'station_wccg'),
  ('show_sunday_snacks', 'host_dj_ike_gda', true, 'station_wccg'),
  ('show_sunday_snacks', 'host_dj_izzynice', false, 'station_wccg'),
  ('show_island_frequency', 'host_dj_daffie', true, 'station_wccg'),
  ('show_mixsquad_radio', 'host_dj_ricovelli', true, 'station_wccg'),
  ('show_mixsquad_radio', 'host_dj_spinwiz', false, 'station_wccg'),
  ('show_mixsquad_radio', 'host_dj_rayn', false, 'station_wccg'),
  ('show_mixsquad_radio', 'host_dj_tommygee', false, 'station_wccg'),
  ('show_mixsquad_radio', 'host_dj_yodo', false, 'station_wccg')
on conflict (show_id, host_id) do update set
  is_primary = excluded.is_primary,
  station_id = excluded.station_id;

-- ── Check-in locations ──────────────────────────────────────────────────────
insert into public.check_in_locations
  (id, name, description, address, lat, lng, points, start_date, end_date, is_active, station_id)
values
  ('loc_crosscreek', 'WCCG at Cross Creek Mall', 'Visit the WCCG street team at Cross Creek Mall for free swag and prizes!', '419 Cross Creek Mall, Fayetteville, NC 28303', 35.0365, -78.9822, 500, '2026-03-01', '2026-12-31', true, 'station_wccg'),
  ('loc_festival_park', 'Friday Night Concert - Festival Park', 'Live music every Friday night at Festival Park. Check in for bonus points!', '335 Ray Ave, Fayetteville, NC 28301', 35.0527, -78.8784, 750, '2026-03-01', '2026-12-31', true, 'station_wccg'),
  ('loc_progressive_mbc', 'WCCG Gospel Caravan - Progressive MBC', 'Join the WCCG Gospel Caravan for an uplifting afternoon of praise and fellowship.', '2640 Raeford Rd, Fayetteville, NC 28305', 35.0703, -78.9134, 500, '2026-03-01', '2026-12-31', true, 'station_wccg'),
  ('loc_hay_street', 'Food Truck Friday - Hay Street', 'Food trucks, music, and community every Friday on Hay Street downtown.', 'Hay Street, Fayetteville, NC 28301', 35.0531, -78.8789, 300, '2026-03-01', '2026-12-31', true, 'station_wccg'),
  ('loc_fort_liberty', 'WCCG at Fort Liberty', 'Supporting our troops! Check in at the WCCG booth near the main gate.', 'Fort Liberty, Fayetteville, NC 28310', 35.1368, -79.0165, 500, '2026-03-01', '2026-12-31', true, 'station_wccg'),
  ('loc_rowan_block_party', 'Summer Block Party - Rowan Street', 'The biggest block party of the summer! DJs, food, games, and a live WCCG broadcast.', 'Rowan Street, Fayetteville, NC 28301', 35.0491, -78.8871, 1000, '2026-06-01', '2026-08-31', true, 'station_wccg')
on conflict (id) do update set
  name        = excluded.name,
  description = excluded.description,
  address     = excluded.address,
  lat         = excluded.lat,
  lng         = excluded.lng,
  points      = excluded.points,
  start_date  = excluded.start_date,
  end_date    = excluded.end_date,
  is_active   = excluded.is_active,
  station_id  = excluded.station_id;

commit;
